apiVersion: v1
items:
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"hospital-appointment","namespace":"argocd"},"spec":{"destination":{"namespace":"hospital","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"appointment-api/helm","repoURL":"https://github.com/sathish-itc/hospital.git","targetRevision":"main"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}
    creationTimestamp: "2026-01-31T16:40:45Z"
    generation: 849
    name: hospital-appointment
    namespace: argocd
    resourceVersion: "1770035776081135000"
    uid: dbf21f9b-e6c4-4bec-90e6-0ecd2f7ca705
  spec:
    destination:
      namespace: hospital
      server: https://kubernetes.default.svc
    project: default
    source:
      path: appointment-api/helm
      repoURL: https://github.com/sathish-itc/hospital.git
      targetRevision: master
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
  status:
    controllerNamespace: argocd
    health:
      lastTransitionTime: "2026-02-02T11:49:24Z"
      status: Healthy
    history:
    - deployStartedAt: "2026-02-02T11:48:58Z"
      deployedAt: "2026-02-02T11:49:02Z"
      id: 0
      initiatedBy:
        automated: true
      revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
      source:
        path: appointment-api/helm
        repoURL: https://github.com/sathish-itc/hospital.git
        targetRevision: master
    operationState:
      finishedAt: "2026-02-02T11:49:02Z"
      message: successfully synced (all tasks run)
      operation:
        initiatedBy:
          automated: true
        retry:
          limit: 5
        sync:
          prune: true
          revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
          source:
            path: appointment-api/helm
            repoURL: https://github.com/sathish-itc/hospital.git
            targetRevision: master
          syncOptions:
          - CreateNamespace=true
      phase: Succeeded
      startedAt: "2026-02-02T11:48:58Z"
      syncResult:
        resources:
        - group: ""
          hookPhase: Running
          kind: ServiceAccount
          message: serviceaccount/hospital-appointment-helm created
          name: hospital-appointment-helm
          namespace: hospital
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ""
          hookPhase: Running
          kind: Service
          message: service/hospital-appointment-helm created
          name: hospital-appointment-helm
          namespace: hospital
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          images:
          - sathish33/appointment_api_image:1
          kind: Deployment
          message: deployment.apps/hospital-appointment-helm created
          name: hospital-appointment-helm
          namespace: hospital
          status: Synced
          syncPhase: Sync
          version: v1
        revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
        source:
          path: appointment-api/helm
          repoURL: https://github.com/sathish-itc/hospital.git
          targetRevision: master
    reconciledAt: "2026-02-02T12:36:15Z"
    resourceHealthSource: appTree
    resources:
    - kind: Service
      name: hospital-appointment-helm
      namespace: hospital
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: hospital-appointment-helm
      namespace: hospital
      status: Synced
      version: v1
    - group: apps
      kind: Deployment
      name: hospital-appointment-helm
      namespace: hospital
      status: Synced
      version: v1
    sourceHydrator: {}
    sourceType: Helm
    summary:
      images:
      - sathish33/appointment_api_image:1
    sync:
      comparedTo:
        destination:
          namespace: hospital
          server: https://kubernetes.default.svc
        source:
          path: appointment-api/helm
          repoURL: https://github.com/sathish-itc/hospital.git
          targetRevision: master
      revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
      status: Synced
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"hospital-frontend","namespace":"argocd"},"spec":{"destination":{"namespace":"hospital","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"frontend-api/helm","repoURL":"https://github.com/sathish-itc/hospital.git","targetRevision":"main"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}
    creationTimestamp: "2026-01-31T16:40:46Z"
    generation: 853
    name: hospital-frontend
    namespace: argocd
    resourceVersion: "1770035832175167002"
    uid: 9181e400-8155-40ef-9b40-0043aaa7a80e
  spec:
    destination:
      namespace: hospital
      server: https://kubernetes.default.svc
    project: default
    source:
      path: frontend-api/helm
      repoURL: https://github.com/sathish-itc/hospital.git
      targetRevision: master
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
  status:
    controllerNamespace: argocd
    health:
      lastTransitionTime: "2026-02-02T11:49:27Z"
      status: Healthy
    history:
    - deployStartedAt: "2026-02-02T11:48:58Z"
      deployedAt: "2026-02-02T11:49:01Z"
      id: 0
      initiatedBy:
        automated: true
      revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
      source:
        path: frontend-api/helm
        repoURL: https://github.com/sathish-itc/hospital.git
        targetRevision: master
    operationState:
      finishedAt: "2026-02-02T11:49:02Z"
      message: successfully synced (all tasks run)
      operation:
        initiatedBy:
          automated: true
        retry:
          limit: 5
        sync:
          prune: true
          revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
          source:
            path: frontend-api/helm
            repoURL: https://github.com/sathish-itc/hospital.git
            targetRevision: master
          syncOptions:
          - CreateNamespace=true
      phase: Succeeded
      startedAt: "2026-02-02T11:48:58Z"
      syncResult:
        resources:
        - group: ""
          hookPhase: Running
          kind: ServiceAccount
          message: serviceaccount/hospital-frontend-helm created
          name: hospital-frontend-helm
          namespace: hospital
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ""
          hookPhase: Running
          kind: Service
          message: service/hospital-frontend-helm created
          name: hospital-frontend-helm
          namespace: hospital
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          images:
          - sathish33/frontend_api_image:2
          kind: Deployment
          message: deployment.apps/hospital-frontend-helm created
          name: hospital-frontend-helm
          namespace: hospital
          status: Synced
          syncPhase: Sync
          version: v1
        revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
        source:
          path: frontend-api/helm
          repoURL: https://github.com/sathish-itc/hospital.git
          targetRevision: master
    reconciledAt: "2026-02-02T12:37:12Z"
    resourceHealthSource: appTree
    resources:
    - kind: Service
      name: hospital-frontend-helm
      namespace: hospital
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: hospital-frontend-helm
      namespace: hospital
      status: Synced
      version: v1
    - group: apps
      kind: Deployment
      name: hospital-frontend-helm
      namespace: hospital
      status: Synced
      version: v1
    sourceHydrator: {}
    sourceType: Helm
    summary:
      images:
      - sathish33/frontend_api_image:2
    sync:
      comparedTo:
        destination:
          namespace: hospital
          server: https://kubernetes.default.svc
        source:
          path: frontend-api/helm
          repoURL: https://github.com/sathish-itc/hospital.git
          targetRevision: master
      revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
      status: Synced
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"hospital-mysql","namespace":"argocd"},"spec":{"destination":{"namespace":"hospital","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"mysql","repoURL":"https://github.com/sathish-itc/hospital.git","targetRevision":"main"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}
    creationTimestamp: "2026-01-31T16:40:46Z"
    generation: 844
    name: hospital-mysql
    namespace: argocd
    resourceVersion: "1770035819193999001"
    uid: a770ca49-4cbe-455f-b4ef-e608c78dd2a2
  spec:
    destination:
      namespace: hospital
      server: https://kubernetes.default.svc
    project: default
    source:
      path: mysql
      repoURL: https://github.com/sathish-itc/hospital.git
      targetRevision: master
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
  status:
    controllerNamespace: argocd
    health:
      lastTransitionTime: "2026-02-02T11:49:00Z"
      status: Healthy
    history:
    - deployStartedAt: "2026-02-02T11:48:57Z"
      deployedAt: "2026-02-02T11:49:00Z"
      id: 0
      initiatedBy:
        automated: true
      revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
      source:
        path: mysql
        repoURL: https://github.com/sathish-itc/hospital.git
        targetRevision: master
    operationState:
      finishedAt: "2026-02-02T11:49:00Z"
      message: successfully synced (all tasks run)
      operation:
        initiatedBy:
          automated: true
        retry:
          limit: 5
        sync:
          prune: true
          revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
          source:
            path: mysql
            repoURL: https://github.com/sathish-itc/hospital.git
            targetRevision: master
          syncOptions:
          - CreateNamespace=true
      phase: Succeeded
      startedAt: "2026-02-02T11:48:57Z"
      syncResult:
        resources:
        - group: ""
          hookPhase: Running
          kind: Service
          message: service/mysql configured
          name: mysql
          namespace: hospital
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          images:
          - mysql:8.0
          kind: Deployment
          message: deployment.apps/mysql configured
          name: mysql
          namespace: hospital
          status: Synced
          syncPhase: Sync
          version: v1
        revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
        source:
          path: mysql
          repoURL: https://github.com/sathish-itc/hospital.git
          targetRevision: master
    reconciledAt: "2026-02-02T12:36:59Z"
    resourceHealthSource: appTree
    resources:
    - kind: Service
      name: mysql
      namespace: hospital
      status: Synced
      version: v1
    - group: apps
      kind: Deployment
      name: mysql
      namespace: hospital
      status: Synced
      version: v1
    sourceHydrator: {}
    sourceType: Directory
    summary:
      images:
      - mysql:8.0
    sync:
      comparedTo:
        destination:
          namespace: hospital
          server: https://kubernetes.default.svc
        source:
          path: mysql
          repoURL: https://github.com/sathish-itc/hospital.git
          targetRevision: master
      revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
      status: Synced
- apiVersion: argoproj.io/v1alpha1
  kind: Application
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"argoproj.io/v1alpha1","kind":"Application","metadata":{"annotations":{},"name":"hospital-patient","namespace":"argocd"},"spec":{"destination":{"namespace":"hospital","server":"https://kubernetes.default.svc"},"project":"default","source":{"path":"patient-api/helm","repoURL":"https://github.com/sathish-itc/hospital.git","targetRevision":"main"},"syncPolicy":{"automated":{"prune":true,"selfHeal":true},"syncOptions":["CreateNamespace=true"]}}}
    creationTimestamp: "2026-01-31T16:40:46Z"
    generation: 851
    name: hospital-patient
    namespace: argocd
    resourceVersion: "1770035788894799001"
    uid: 686ebc6f-fae1-49f2-ae37-5da1cbb0da2e
  spec:
    destination:
      namespace: hospital
      server: https://kubernetes.default.svc
    project: default
    source:
      path: patient-api/helm
      repoURL: https://github.com/sathish-itc/hospital.git
      targetRevision: master
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
      - CreateNamespace=true
  status:
    controllerNamespace: argocd
    health:
      lastTransitionTime: "2026-02-02T11:49:23Z"
      status: Healthy
    history:
    - deployStartedAt: "2026-02-02T11:48:58Z"
      deployedAt: "2026-02-02T11:49:01Z"
      id: 0
      initiatedBy:
        automated: true
      revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
      source:
        path: patient-api/helm
        repoURL: https://github.com/sathish-itc/hospital.git
        targetRevision: master
    operationState:
      finishedAt: "2026-02-02T11:49:01Z"
      message: successfully synced (all tasks run)
      operation:
        initiatedBy:
          automated: true
        retry:
          limit: 5
        sync:
          prune: true
          revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
          source:
            path: patient-api/helm
            repoURL: https://github.com/sathish-itc/hospital.git
            targetRevision: master
          syncOptions:
          - CreateNamespace=true
      phase: Succeeded
      startedAt: "2026-02-02T11:48:58Z"
      syncResult:
        resources:
        - group: ""
          hookPhase: Running
          kind: ServiceAccount
          message: serviceaccount/hospital-patient-helm created
          name: hospital-patient-helm
          namespace: hospital
          status: Synced
          syncPhase: Sync
          version: v1
        - group: ""
          hookPhase: Running
          kind: Service
          message: service/hospital-patient-helm created
          name: hospital-patient-helm
          namespace: hospital
          status: Synced
          syncPhase: Sync
          version: v1
        - group: apps
          hookPhase: Running
          images:
          - sathish33/patient_api_image:1
          kind: Deployment
          message: deployment.apps/hospital-patient-helm created
          name: hospital-patient-helm
          namespace: hospital
          status: Synced
          syncPhase: Sync
          version: v1
        revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
        source:
          path: patient-api/helm
          repoURL: https://github.com/sathish-itc/hospital.git
          targetRevision: master
    reconciledAt: "2026-02-02T12:36:28Z"
    resourceHealthSource: appTree
    resources:
    - kind: Service
      name: hospital-patient-helm
      namespace: hospital
      status: Synced
      version: v1
    - kind: ServiceAccount
      name: hospital-patient-helm
      namespace: hospital
      status: Synced
      version: v1
    - group: apps
      kind: Deployment
      name: hospital-patient-helm
      namespace: hospital
      status: Synced
      version: v1
    sourceHydrator: {}
    sourceType: Helm
    summary:
      images:
      - sathish33/patient_api_image:1
    sync:
      comparedTo:
        destination:
          namespace: hospital
          server: https://kubernetes.default.svc
        source:
          path: patient-api/helm
          repoURL: https://github.com/sathish-itc/hospital.git
          targetRevision: master
      revision: 150bc57ec5ddc9c0f4d1cfb0bcb25423c681842f
      status: Synced
kind: List
metadata:
  resourceVersion: ""
