image:
  repository: omagu/patient-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 3000
  type: ClusterIP

env:
  DB_SERVER: hospital-ui-hpm-sqlserver

sqlserver:
  enabled: false

ingress:
  enabled: false
  hosts:
    - host: hospital.local
      paths:
        - path: /patient
          pathType: Prefix

serviceAccount:
  create: true
  name: "hospital-patient-sa"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
