image:
  repository: omagu/appointment-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  port: 3001
  type: ClusterIP

ingress:
  enabled: false
  hosts:
    - host: hospital.local
      paths:
        - path: /appointment
          pathType: Prefix

serviceAccount:
  create: true
  name: "hospital-appointment-sa"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 80
